"""Initial migration

Revision ID: 5ef0269c3bc1
Revises: 
Create Date: 2025-09-10 19:33:51.603436

"""
from alembic import op
import sqlalchemy as sa


revision = '5ef0269c3bc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('restrict_following', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_terms_id'), 'monitored_terms', ['id'], unique=False)
    op.create_index(op.f('ix_monitored_terms_keyword'), 'monitored_terms', ['keyword'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('tweets_raw', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['monitored_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_monitored_terms_keyword'), table_name='monitored_terms')
    op.drop_index(op.f('ix_monitored_terms_id'), table_name='monitored_terms')
    op.drop_table('monitored_terms')
    # ### end Alembic commands ###